version: '2'
services:
  geoserver:
    scale: 1
    start_on_create: true
  geoserver-balancer:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: geoserver
        priority: 1
        protocol: http
        service: geoserver
        source_port: 8080
        target_port: 8080
      - hostname: 88.99.166.60
        priority: 2
        protocol: http
        service: geoserver
        source_port: 30008
        target_port: 8080
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  django:
    scale: 1
    start_on_create: true
  elasticsearch:
    scale: 1
    start_on_create: true
  nginx:
    scale: 1
    start_on_create: true
  rabbitmq:
    scale: 1
    start_on_create: true
  postgres:
    scale: 1
    start_on_create: true
  dbbackups:
    scale: 1
    start_on_create: true
